simulation:
  time_step: 15min
  start_date: 01-01-2020
  time_horizon: 20
  demand_curve_file: Input/demand_qc_kw_el.csv
users:
- user0:
    id: '0'
    carriers:
      electricity:
        column: user0
  user1:
    id: '1'
    carriers:
      electricity:
        column: user1
  user2:
    id: '2'
    carriers:
      electricity:
        column: user2
  user3:
    id: '3'
    carriers:
      electricity:
        column: user3
  user4:
    id: '4'
    carriers:
      electricity:
        column: user4
  user5:
    id: '5'
    carriers:
      electricity:
        column: user5
  user6:
    id: '6'
    carriers:
      electricity:
        column: user6
  user7:
    id: '7'
    carriers:
      electricity:
        column: user7
  user8:
    id: '8'
    carriers:
      electricity:
        column: user8
  user9:
    id: '9'
    carriers:
      electricity:
        column: user9
  user10:
    id: '10'
    carriers:
      electricity:
        column: user10
  user11:
    id: '11'
    carriers:
      electricity:
        column: user11
  user12:
    id: '12'
    carriers:
      electricity:
        column: user12
  user13:
    id: '13'
    carriers:
      electricity:
        column: user13
  user14:
    id: '14'
    carriers:
      electricity:
        column: user14
  user15:
    id: '15'
    carriers:
      electricity:
        column: user15
  user16:
    id: '16'
    carriers:
      electricity:
        column: user16
  user17:
    id: '17'
    carriers:
      electricity:
        column: user17
  user18:
    id: '18'
    carriers:
      electricity:
        column: user18
  user19:
    id: '19'
    carriers:
      electricity:
        column: user19
  user20:
    id: '20'
    carriers:
      electricity:
        column: user20
  user21:
    id: '21'
    carriers:
      electricity:
        column: user21
  user22:
    id: '22'
    carriers:
      electricity:
        column: user22
  user23:
    id: '23'
    carriers:
      electricity:
        column: user23
  user24:
    id: '24'
    carriers:
      electricity:
        column: user24
  user25:
    id: '25'
    carriers:
      electricity:
        column: user25
  user26:
    id: '26'
    carriers:
      electricity:
        column: user26
  user27:
    id: '27'
    carriers:
      electricity:
        column: user27
  user28:
    id: '28'
    carriers:
      electricity:
        column: user28
  user29:
    id: '29'
    carriers:
      electricity:
        column: user29
  user30:
    id: '30'
    carriers:
      electricity:
        column: user30
  user31:
    id: '31'
    carriers:
      electricity:
        column: user31
  user32:
    id: '32'
    carriers:
      electricity:
        column: user32
  user33:
    id: '33'
    carriers:
      electricity:
        column: user33
  user34:
    id: '34'
    carriers:
      electricity:
        column: user34
  user35:
    id: '35'
    carriers:
      electricity:
        column: user35
  user36:
    id: '36'
    carriers:
      electricity:
        column: user36
  user37:
    id: '37'
    carriers:
      electricity:
        column: user37
  user38:
    id: '38'
    carriers:
      electricity:
        column: user38
  user39:
    id: '39'
    carriers:
      electricity:
        column: user39
  user40:
    id: '40'
    carriers:
      electricity:
        column: user40
  user41:
    id: '41'
    carriers:
      electricity:
        column: user41
  user42:
    id: '42'
    carriers:
      electricity:
        column: user42
  user43:
    id: '43'
    carriers:
      electricity:
        column: user43
  user44:
    id: '44'
    carriers:
      electricity:
        column: user44
  user45:
    id: '45'
    carriers:
      electricity:
        column: user45
  user46:
    id: '46'
    carriers:
      electricity:
        column: user46
  user47:
    id: '47'
    carriers:
      electricity:
        column: user47
  user48:
    id: '48'
    carriers:
      electricity:
        column: user48
  user49:
    id: '49'
    carriers:
      electricity:
        column: user49
  user50:
    id: '50'
    carriers:
      electricity:
        column: user50
  user51:
    id: '51'
    carriers:
      electricity:
        column: user51
systems:
- pv1:
    tech:
      id: pv1
      lat: 41.9027835
      lon: 12.496365
      n_series: 30
      n_parallel: 10
      tilt: 30
      azimuth: 0
    economics:
      cap_cost: 1500
      opex_cost: 40
      inc_year: 9000.0
      inc_start_end:
      - 1
      - 10
      tax_year: 0
      other_cost:
        item1:
          unit: 120.0
          cost_unit: 350
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
  pv2:
    tech:
      id: pv1
      lat: 41.891159
      lon: 12.492059
      n_series: 13
      n_parallel: 12
      tilt: 30
      azimuth: 0
    economics:
      cap_cost: 1500
      opex_cost: 40
      inc_year: 4680.000000000001
      inc_start_end:
      - 1
      - 10
      tax_year: 0
      other_cost:
        item1:
          unit: 62.400000000000006
          cost_unit: 350
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
  pv3:
    tech:
      id: pv1
      lat: 41.893483
      lon: 12.492477
      n_series: 11
      n_parallel: 11
      tilt: 30
      azimuth: 0
    economics:
      cap_cost: 1500
      opex_cost: 40
      inc_year: 0
      inc_start_end:
      - 0
      - 0
      tax_year: 0
      other_cost:
        item1:
          unit: 48.400000000000006
          cost_unit: 350
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
bess:
- bess1:
    tech:
      id: bess1
      cap_module: 2.56
      v: 25.6
      i_max: 100
      i_min: 5
      soc_in: 0.2
      soc_max: 0.8
      soc_min: 0.2
      n_series: 2
      n_parallel: 2
    economics:
      cap_cost: 720
      opex_cost: 20
      inc_year: 368.64
      inc_start_end:
      - 1
      - 10
      tax_year: 10
      other_cost:
        item1:
          unit: 10.24
          cost_unit: 720
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
  bess2:
    tech:
      id: bess2
      cap_module: 2.56
      v: 25.6
      i_max: 100
      i_min: 5
      soc_in: 0.2
      soc_max: 1
      soc_min: 0.2
      n_series: 2
      n_parallel: 2
    economics:
      cap_cost: 720
      opex_cost: 20
      inc_year: 368.64
      inc_start_end:
      - 1
      - 10
      tax_year: 10
      other_cost:
        item1:
          unit: 10.24
          cost_unit: 720
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
  bess3:
    tech:
      id: bess2
      cap_module: 2.56
      v: 25.6
      i_max: 100
      i_min: 5
      soc_in: 0.2
      soc_max: 1
      soc_min: 0.2
      n_series: 2
      n_parallel: 2
    economics:
      cap_cost: 720
      opex_cost: 20
      inc_year: 0
      inc_start_end:
      - 0
      - 0
      tax_year: 10
      other_cost:
        item1:
          unit: 10.24
          cost_unit: 720
          dur:
          - 10
          - 10
      other_rev:
        item1:
          unit: 0
          rev_unit: 0
          dur:
          - 0
          - 0
prosumers:
- prosumer1:
    tech:
      id: prosumer1
      carriers:
      - electricity
      users:
      - user0
      systems:
      - pv1
      bess:
      - bess1
      - bess2
    economics:
      tax_rate: 0.2
      int_rate: 0.03
      carriers_and_costs:
        electricity:
          decay: 0.02
          price_buy: 130
          price_sold: 104
      other_capex_perc:
      - 0
  prosumer2:
    tech:
      id: prosumer2
      carriers:
      - electricity
      users:
      - user1
      systems:
      - pv2
      bess: []
    economics:
      tax_rate: 0.2
      int_rate: 0.03
      carriers_and_costs:
        electricity:
          decay: 0.02
          price_buy: 130
          price_sold: 104
      other_capex_perc:
      - 0.02
rec:
- rec1:
    tech:
      id: rec1
      carriers:
      - electricity
      prosumers:
      - prosumer1
      - prosumer2
      consumers:
      - user2
      - user3
      - user4
      - user5
      - user6
      - user7
      - user8
      - user9
      - user10
      - user11
      - user12
      - user13
      - user14
      - user15
      - user16
      - user17
      - user18
      - user19
      - user20
      - user21
      - user22
      - user23
      - user24
      - user25
      - user26
      - user27
      - user28
      - user29
      - user30
      - user31
      - user32
      - user33
      - user34
      - user35
      - user36
      - user37
      - user38
      - user39
      - user40
      - user41
      - user42
      - user43
      - user44
      - user45
      - user46
      - user47
      - user48
      - user49
      - user50
      - user51
      rec_systems:
      - pv3
      bess:
      - bess3
    economics:
      tax_rate: 0.2
      int_rate: 0.03
      carriers_and_costs:
        electricity:
          decay: 0.02
          price_buy: 130
          price_sold: 104
      other_capex_perc:
      - 0.02
